# (from: https://docs.travis-ci.com/user/languages/haskell/)

language: haskell

ghc:
- "8.2"

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.cabal

before_install:
- cabal update

install:
- cabal install --only-dependencies --enable-test

script:
# Show GHC version
 - ghc --version
 # Test
 - cabal test --show-details=streaming
