# (from: https://docs.travis-ci.com/user/languages/haskell/)
# (from: https://github.com/rickardlindberg/alldoc/blob/22607f07021563b07f493956e9106819cedc6182/.travis.yml)
language: haskell

ghc:
- "8.2"

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.cabal

before_install:
- cabal update
- cabal install cabal-install

install:
- ~/.cabal/bin/cabal install --only-dependencies --enable-test

script:
# Show GHC version
 - ghc --version
 # Test
 - ~/.cabal/bin/cabal test --show-details=streaming
